apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-helm-api-operator
  labels:
      name: ibm-helm-api-operator
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/managed-by: "{{ .Release.Service }}"
      app.kubernetes.io/name: helmapis.operator.ibm.com
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-helm-api-operator
  template:
    metadata:
      labels:
        name: ibm-helm-api-operator
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/managed-by: "{{ .Release.Service }}"
        app.kubernetes.io/name: helmapis.operator.ibm.com
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.3.0"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-helm-api-operator
      containers:
        - name: ibm-helm-api-operator
          # Replace this with the built image name
          image: quay.io/opencloudio/ibm-helm-api-operator:3.5.0 #TODO change back to 3.6.0 when available
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-helm-api-operator"
