apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-helm-api-operator
  labels:
      name: ibm-helm-api-operator
      app.kubernetes.io/instance: helm-api
      app.kubernetes.io/managed-by: helmapis.operator.ibm.com
      app.kubernetes.io/name: helmapis.operator.ibm.com
subjects:
- kind: ServiceAccount
  name: ibm-helm-api-operator
  namespace: ibm-common-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-helm-api-operator