apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-helm-api-operator
  labels:
      name: ibm-helm-api-operator
      app.kubernetes.io/instance: helmapis.operator.ibm.com
      app.kubernetes.io/managed-by: helmapis.operator.ibm.com
      app.kubernetes.io/name: helmapis.operator.ibm.com
